#!/bin/bash
# Removes files generated by build.sh (ANTLR output + compiled binary)
# and by run.sh (assembly + assembled executables), restoring the
# project to its fresh/pre-build state.
set -e
cd "$(dirname "$0")"

GENERATED=(
    # --- generated by build.sh: antlr4 -Dlanguage=Cpp -visitor -no-listener CSubset.g4 ---
    CSubsetLexer.cpp
    CSubsetLexer.h
    CSubsetLexer.interp
    CSubsetLexer.tokens
    CSubsetParser.cpp
    CSubsetParser.h
    CSubset.interp
    CSubset.tokens
    CSubsetVisitor.cpp
    CSubsetVisitor.h
    CSubsetBaseVisitor.cpp
    CSubsetBaseVisitor.h
    # --- generated by build.sh: g++ compile output ---
    icg.out
    # --- generated by run.sh: ./icg.out <input.c> ---
    code.asm
    optimized_code.asm
    # --- generated by run.sh: fasm assembling ---
    code.out
    optimized_code.out
)

echo "Removing generated files..."
for f in "${GENERATED[@]}"; do
    if [ -e "$f" ]; then
        rm -v "$f"
    fi
done

echo "Clean complete. Project restored to fresh state."
